### ISSUE TITLE
Separator blocks show as broken in the editor

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/anima#292]
After the latest updates to WP 5.8, Rosa2 1.12.4 and Nova Blocks 1.12.7, all already added separator blocks have the following error next to them:

<img width="972" alt="CleanShot 2021-07-27 at 14 52 46@2x" src="https://user-images.githubusercontent.com/53944294/127149234-8877c3f9-7ec9-4e39-a816-2d3ad3928dfb.png">

Clicking _Attempt Block Recovery_ does the trick but maybe there's something we can do to avoid this from happening.

**Comment by madalingorbanescu** [comment]
Nothing to worry.

@andreiungurianu already made an article about this: https://pixelgrade.com/docs/rosa2/troubleshooting/unexpected-invalid-content-block-error/

I am going to close this, since is not really an issue.
