### ISSUE TITLE
HTML Anchor advanced option missing form Hero

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/anima#324]
I updated the existing [documentation](https://pixelgrade.com/docs/rosa-lt/guides-and-resources/one-page-website/) on building a one-page website and noticed that the advice I gave there no longer applies.

Particularly, how to add HTML anchors to a Hero card to help create one-page websites. The option detailed there no longer exists.
![CleanShot 2022-06-16 at 15 52 01](https://user-images.githubusercontent.com/53944294/174073700-9d429f97-41ee-44e6-aeca-ae642aefaa1f.png)

I'm not sure if this is WordPress related or if we removed it by mistake, but I think this is an important feature.

@georgeolaru maybe you can advise on this.

**Comment by georgeolaru** [comment]
@andreiungurianu Thanks for noticing this! I think the anchor links are necessary for most blocks, and we should add them for both `Supernova` (parent) and `Supernova Item` (child) blocks.

@razwan fixed this on the Nova Blocks plugin, and the changes will be available in the next update. For reference, see the following commits: 
- https://github.com/pixelgrade/nova-blocks/commit/484c5387d2f8931ffbbe44c3dbc05f560c11878e 
- https://github.com/pixelgrade/nova-blocks/commit/3078f1f778da7925a235ee662d200b38984e6d47
- https://github.com/pixelgrade/nova-blocks/commit/45070a208f02318ceacc761ccc7d84a07e17101e
